name: Actualizar Canales Automatizado

on:
  schedule:
    # Se ejecuta automáticamente cada 6 horas
    - cron: '0 */6 * * *'
  workflow_dispatch: # Permite activarlo manualmente

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Ejecutar script cazador
      run: python actualizar.py

    - name: Guardar cambios automáticamente
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Robot: Token de Color Visión actualizado automáticamente"
        file_pattern: 'lista.m3u'
