name: Actualizar Canales Automatizado

on:
  schedule:
    # Se ejecuta automáticamente cada 6 horas
    - cron: '0 */6 * * *'
  workflow_dispatch: # Permite activarlo manualmente

# Esto le da explícitamente permisos de escritura al robot
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Ejecutar script cazador
      run: python actualizar.py

    - name: Guardar cambios en GitHub
      run: |
        git config --global user.name 'GitHub Action Robot'
        git config --global user.email 'action@github.com'
        git add lista.m3u
        git diff --quiet && git diff --staged --quiet || (git commit -m "Robot: Token de Color Visión actualizado automáticamente" && git push)
