name: Actualizar Canales Automatizado

on:
  schedule:
    # Se ejecuta automáticamente cada 6 horas
    - cron: '0 */6 * * *'
  workflow_dispatch: # Permite activarlo manualmente

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Ejecutar script cazador
      run: python actualizar.py

    - name: Guardar cambios en GitHub
      run: |
        git config --global user.name 'GitHub Action Robot'
        git config --global user.email 'action@github.com'
        git add lista.m3u
        
        # Verificamos si hubo cambios antes de subir
        if ! git diff --quiet || ! git diff --staged --quiet; then
          git commit -m "Robot: Token de Color Visión actualizado automáticamente"
          # Forzamos el empuje usando el token secreto del sistema
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
        else
          print "No hubo cambios en el enlace hoy."
        fi
